"""add pricing watchlist and observations

Revision ID: 4ada7231ba4e
Revises: ee6bfae1280f
Create Date: 2026-09-15 20:41:51.066494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ada7231ba4e'
down_revision: Union[str, None] = 'ee6bfae1280f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_model_id', sa.Integer(), nullable=False),
    sa.Column('storage', sa.String(length=20), nullable=True),
    sa.Column('condition_bucket', sa.Enum('USED', 'FAULTY', name='priceconditionbucket'), nullable=False),
    sa.Column('source', sa.Enum('SOLD', 'ACTIVE_LISTING_ESTIMATE', name='pricedatasource'), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('median_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=6), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['phone_model_id'], ['phone_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_observations_condition_bucket'), 'price_observations', ['condition_bucket'], unique=False)
    op.create_index(op.f('ix_price_observations_observed_at'), 'price_observations', ['observed_at'], unique=False)
    op.create_index(op.f('ix_price_observations_phone_model_id'), 'price_observations', ['phone_model_id'], unique=False)
    op.create_index(op.f('ix_price_observations_storage'), 'price_observations', ['storage'], unique=False)
    op.create_table('price_watchlist_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_model_id', sa.Integer(), nullable=False),
    sa.Column('storage', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by_discord_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['phone_model_id'], ['phone_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_watchlist_entries')
    op.drop_index(op.f('ix_price_observations_storage'), table_name='price_observations')
    op.drop_index(op.f('ix_price_observations_phone_model_id'), table_name='price_observations')
    op.drop_index(op.f('ix_price_observations_observed_at'), table_name='price_observations')
    op.drop_index(op.f('ix_price_observations_condition_bucket'), table_name='price_observations')
    op.drop_table('price_observations')
    # ### end Alembic commands ###
