"""initial schema

Revision ID: ee6bfae1280f
Revises: 
Create Date: 2026-09-12 07:23:47.162030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee6bfae1280f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorized_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_user_id', sa.BigInteger(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('added_by_discord_id', sa.BigInteger(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authorized_users_discord_user_id'), 'authorized_users', ['discord_user_id'], unique=True)
    op.create_table('bot_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id')
    )
    op.create_table('business_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('condition_grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('expense_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('id_sequences',
    sa.Column('prefix', sa.String(length=10), nullable=False),
    sa.Column('next_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('prefix')
    )
    op.create_table('inventory_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('actor_discord_id', sa.BigInteger(), nullable=True),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(length=20), nullable=False),
    sa.Column('related_entity_type', sa.String(length=20), nullable=True),
    sa.Column('related_entity_id', sa.String(length=20), nullable=True),
    sa.Column('previous_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_events_entity_id'), 'inventory_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_inventory_events_entity_type'), 'inventory_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_inventory_events_event_type'), 'inventory_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_inventory_events_occurred_at'), 'inventory_events', ['occurred_at'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('zone', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_id', sa.String(length=20), nullable=False),
    sa.Column('supplier', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('expected_delivery', sa.Date(), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_internal_id'), 'orders', ['internal_id'], unique=True)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('part_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('phone_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('variant', sa.String(length=50), nullable=True),
    sa.Column('default_sale_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manufacturer', 'model', 'variant', name='uq_phone_model')
    )
    op.create_table('test_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('workflow_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_terminal', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'code', name='uq_workflow_status')
    )
    op.create_table('donors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_id', sa.String(length=20), nullable=False),
    sa.Column('manufacturer', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('variant', sa.String(length=50), nullable=True),
    sa.Column('storage', sa.String(length=20), nullable=True),
    sa.Column('colour', sa.String(length=40), nullable=True),
    sa.Column('imei', sa.String(length=20), nullable=True),
    sa.Column('serial_number', sa.String(length=40), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('seller_source', sa.String(length=150), nullable=True),
    sa.Column('fault_description', sa.Text(), nullable=True),
    sa.Column('current_status', sa.String(length=40), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('torn_down_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donors_current_status'), 'donors', ['current_status'], unique=False)
    op.create_index(op.f('ix_donors_internal_id'), 'donors', ['internal_id'], unique=True)
    op.create_table('order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('part_type_id', sa.Integer(), nullable=False),
    sa.Column('phone_model_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('received_quantity', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['part_type_id'], ['part_types.id'], ),
    sa.ForeignKeyConstraint(['phone_model_id'], ['phone_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_id', sa.String(length=20), nullable=False),
    sa.Column('manufacturer', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('variant', sa.String(length=50), nullable=True),
    sa.Column('storage', sa.String(length=20), nullable=True),
    sa.Column('colour', sa.String(length=40), nullable=True),
    sa.Column('imei', sa.String(length=20), nullable=True),
    sa.Column('serial_number', sa.String(length=40), nullable=True),
    sa.Column('carrier', sa.String(length=60), nullable=True),
    sa.Column('lock_status', sa.Enum('UNLOCKED', 'LOCKED', 'UNKNOWN', name='lockstatus'), nullable=False),
    sa.Column('battery_health', sa.Integer(), nullable=True),
    sa.Column('cosmetic_condition', sa.String(length=100), nullable=True),
    sa.Column('functional_condition', sa.String(length=100), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('seller_source', sa.String(length=150), nullable=True),
    sa.Column('acquisition_type', sa.Enum('RESALE', 'REPAIR', 'DONOR', name='acquisitiontype'), nullable=False),
    sa.Column('current_status', sa.String(length=40), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phones_current_status'), 'phones', ['current_status'], unique=False)
    op.create_index(op.f('ix_phones_imei'), 'phones', ['imei'], unique=False)
    op.create_index(op.f('ix_phones_internal_id'), 'phones', ['internal_id'], unique=True)
    op.create_index(op.f('ix_phones_serial_number'), 'phones', ['serial_number'], unique=False)
    op.create_table('pricing_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_model_id', sa.Integer(), nullable=True),
    sa.Column('target_margin_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('min_profit_gbp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('min_roi_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('default_sale_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['phone_model_id'], ['phone_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_id', sa.String(length=20), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('phone_id', sa.Integer(), nullable=True),
    sa.Column('donor_id', sa.Integer(), nullable=True),
    sa.Column('incurred_at', sa.Date(), nullable=False),
    sa.Column('created_by_discord_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], ),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ),
    sa.ForeignKeyConstraint(['phone_id'], ['phones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_internal_id'), 'expenses', ['internal_id'], unique=True)
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_id', sa.String(length=20), nullable=False),
    sa.Column('phone_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('condition_text', sa.String(length=100), nullable=True),
    sa.Column('category_id', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=6), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('shipping_policy_id', sa.String(length=80), nullable=True),
    sa.Column('payment_policy_id', sa.String(length=80), nullable=True),
    sa.Column('return_policy_id', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('ebay_listing_id', sa.String(length=60), nullable=True),
    sa.Column('ebay_offer_id', sa.String(length=60), nullable=True),
    sa.Column('ebay_sku', sa.String(length=60), nullable=True),
    sa.Column('ebay_url', sa.String(length=300), nullable=True),
    sa.Column('listed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_discord_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['phone_id'], ['phones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ebay_sku')
    )
    op.create_index(op.f('ix_listings_ebay_listing_id'), 'listings', ['ebay_listing_id'], unique=True)
    op.create_index(op.f('ix_listings_internal_id'), 'listings', ['internal_id'], unique=True)
    op.create_index(op.f('ix_listings_phone_id'), 'listings', ['phone_id'], unique=False)
    op.create_index(op.f('ix_listings_status'), 'listings', ['status'], unique=False)
    op.create_table('repairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_id', sa.String(length=20), nullable=False),
    sa.Column('phone_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('labour_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('external_repair_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['phone_id'], ['phones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repairs_internal_id'), 'repairs', ['internal_id'], unique=True)
    op.create_index(op.f('ix_repairs_phone_id'), 'repairs', ['phone_id'], unique=False)
    op.create_index(op.f('ix_repairs_status'), 'repairs', ['status'], unique=False)
    op.create_table('test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_id', sa.Integer(), nullable=False),
    sa.Column('test_definition_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.Enum('PASS', 'FAIL', 'NOT_TESTED', 'NOT_APPLICABLE', name='testoutcome'), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('tested_by_discord_id', sa.BigInteger(), nullable=True),
    sa.Column('tested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['phone_id'], ['phones.id'], ),
    sa.ForeignKeyConstraint(['test_definition_id'], ['test_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_results_phone_id'), 'test_results', ['phone_id'], unique=False)
    op.create_table('parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_id', sa.String(length=20), nullable=False),
    sa.Column('part_type_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('DONOR', 'PURCHASED', 'EXISTING_STOCK', 'OTHER', name='partsourcetype'), nullable=False),
    sa.Column('source_donor_id', sa.Integer(), nullable=True),
    sa.Column('source_phone_id', sa.Integer(), nullable=True),
    sa.Column('source_order_line_id', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('condition', sa.String(length=100), nullable=True),
    sa.Column('grade_code', sa.String(length=10), nullable=True),
    sa.Column('testing_status', sa.Enum('PASS', 'FAIL', 'NOT_TESTED', 'NOT_APPLICABLE', name='testoutcome'), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('installed_phone_id', sa.Integer(), nullable=True),
    sa.Column('reserved_for_repair_id', sa.Integer(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['installed_phone_id'], ['phones.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['part_type_id'], ['part_types.id'], ),
    sa.ForeignKeyConstraint(['reserved_for_repair_id'], ['repairs.id'], ),
    sa.ForeignKeyConstraint(['source_donor_id'], ['donors.id'], ),
    sa.ForeignKeyConstraint(['source_order_line_id'], ['order_lines.id'], ),
    sa.ForeignKeyConstraint(['source_phone_id'], ['phones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parts_internal_id'), 'parts', ['internal_id'], unique=True)
    op.create_index(op.f('ix_parts_status'), 'parts', ['status'], unique=False)
    op.create_table('phone_faults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('required_part_type_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', 'WONT_FIX', name='faultstatus'), nullable=False),
    sa.Column('repair_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['phone_id'], ['phones.id'], ),
    sa.ForeignKeyConstraint(['repair_id'], ['repairs.id'], ),
    sa.ForeignKeyConstraint(['required_part_type_id'], ['part_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_id', sa.String(length=20), nullable=False),
    sa.Column('phone_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('ebay_order_id', sa.String(length=60), nullable=True),
    sa.Column('source', sa.Enum('EBAY_SYNC', 'MANUAL', name='salesource'), nullable=False),
    sa.Column('status', sa.Enum('PENDING_SHIPMENT', 'SHIPPED', 'COMPLETE', 'REFUNDED', name='salestatus'), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ebay_fees', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('postage_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('packaging_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('other_fees', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('buyer_reference', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['phone_id'], ['phones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_ebay_order_id'), 'sales', ['ebay_order_id'], unique=True)
    op.create_index(op.f('ix_sales_internal_id'), 'sales', ['internal_id'], unique=True)
    op.create_index(op.f('ix_sales_phone_id'), 'sales', ['phone_id'], unique=False)
    op.create_table('cost_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.Enum('MANUAL', 'PRO_RATA', name='allocationmethod'), nullable=False),
    sa.Column('donor_total_cost_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_by_discord_id', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_allocations_batch_id'), 'cost_allocations', ['batch_id'], unique=False)
    op.create_table('part_compatible_models',
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('phone_model_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['phone_model_id'], ['phone_models.id'], ),
    sa.PrimaryKeyConstraint('part_id', 'phone_model_id')
    )
    op.create_table('repair_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repair_id', sa.Integer(), nullable=False),
    sa.Column('required_part_type_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('REQUIRED', 'RESERVED', 'INSTALLED', 'REMOVED', 'CANCELLED', name='repairpartlinestatus'), nullable=False),
    sa.Column('cost_at_installation', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('reserved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['repair_id'], ['repairs.id'], ),
    sa.ForeignKeyConstraint(['required_part_type_id'], ['part_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale_profit_breakdowns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('purchase_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('donor_allocated_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('purchased_part_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('repair_labour_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('external_repair_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('shipping_in_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('shipping_out_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('packaging_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ebay_fees', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('other_fees', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('other_expenses', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sale_revenue', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gross_profit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_profit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('margin_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('roi_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sale_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale_profit_breakdowns')
    op.drop_table('repair_parts')
    op.drop_table('part_compatible_models')
    op.drop_index(op.f('ix_cost_allocations_batch_id'), table_name='cost_allocations')
    op.drop_table('cost_allocations')
    op.drop_index(op.f('ix_sales_phone_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_internal_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_ebay_order_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_table('phone_faults')
    op.drop_index(op.f('ix_parts_status'), table_name='parts')
    op.drop_index(op.f('ix_parts_internal_id'), table_name='parts')
    op.drop_table('parts')
    op.drop_index(op.f('ix_test_results_phone_id'), table_name='test_results')
    op.drop_table('test_results')
    op.drop_index(op.f('ix_repairs_status'), table_name='repairs')
    op.drop_index(op.f('ix_repairs_phone_id'), table_name='repairs')
    op.drop_index(op.f('ix_repairs_internal_id'), table_name='repairs')
    op.drop_table('repairs')
    op.drop_index(op.f('ix_listings_status'), table_name='listings')
    op.drop_index(op.f('ix_listings_phone_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_internal_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_ebay_listing_id'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_expenses_internal_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_table('pricing_rules')
    op.drop_index(op.f('ix_phones_serial_number'), table_name='phones')
    op.drop_index(op.f('ix_phones_internal_id'), table_name='phones')
    op.drop_index(op.f('ix_phones_imei'), table_name='phones')
    op.drop_index(op.f('ix_phones_current_status'), table_name='phones')
    op.drop_table('phones')
    op.drop_table('order_lines')
    op.drop_index(op.f('ix_donors_internal_id'), table_name='donors')
    op.drop_index(op.f('ix_donors_current_status'), table_name='donors')
    op.drop_table('donors')
    op.drop_table('workflow_statuses')
    op.drop_table('test_definitions')
    op.drop_table('phone_models')
    op.drop_table('part_types')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_internal_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('locations')
    op.drop_index(op.f('ix_inventory_events_occurred_at'), table_name='inventory_events')
    op.drop_index(op.f('ix_inventory_events_event_type'), table_name='inventory_events')
    op.drop_index(op.f('ix_inventory_events_entity_type'), table_name='inventory_events')
    op.drop_index(op.f('ix_inventory_events_entity_id'), table_name='inventory_events')
    op.drop_table('inventory_events')
    op.drop_table('id_sequences')
    op.drop_table('expense_categories')
    op.drop_table('condition_grades')
    op.drop_table('business_settings')
    op.drop_table('bot_channels')
    op.drop_index(op.f('ix_authorized_users_discord_user_id'), table_name='authorized_users')
    op.drop_table('authorized_users')
    # ### end Alembic commands ###
